// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzNHj6tPvAVdp51MO_wPQAIjebzDU0N0',
    appId: '1:408002397700:web:267cf76c103f59cda01751',
    messagingSenderId: '408002397700',
    projectId: 'task-3e13f',
    authDomain: 'task-3e13f.firebaseapp.com',
    storageBucket: 'task-3e13f.firebasestorage.app',
    measurementId: 'G-B8ZKNJGEL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyD5ut-pC9MBE7S4D9xaMPY8caExQbGI',
    appId: '1:408002397700:android:b7546f48873df95fa01751',
    messagingSenderId: '408002397700',
    projectId: 'task-3e13f',
    storageBucket: 'task-3e13f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_iJfIDZo29eLsljfLPc7PRO25jKutsB4',
    appId: '1:408002397700:ios:fcb06a5703de7c88a01751',
    messagingSenderId: '408002397700',
    projectId: 'task-3e13f',
    storageBucket: 'task-3e13f.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_iJfIDZo29eLsljfLPc7PRO25jKutsB4',
    appId: '1:408002397700:ios:fcb06a5703de7c88a01751',
    messagingSenderId: '408002397700',
    projectId: 'task-3e13f',
    storageBucket: 'task-3e13f.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzNHj6tPvAVdp51MO_wPQAIjebzDU0N0',
    appId: '1:408002397700:web:d536a469852f19b7a01751',
    messagingSenderId: '408002397700',
    projectId: 'task-3e13f',
    authDomain: 'task-3e13f.firebaseapp.com',
    storageBucket: 'task-3e13f.firebasestorage.app',
    measurementId: 'G-25VX22XD0V',
  );
}
